spring:
  profiles:
    active:
      - dev
---

server:
  port: 8001
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yangpaul8001?useSSL=false&serverTimezone=GMT
    username: root
    password: yangpaul
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: config-dept-client
eureka:
  client:
    service-url:
      defaultZone: http://yangpaul:yangpaul@localhost:7001/eureka,http://yangpaul:yangpaul@localhost:7002/eureka,http://yangpaul:yangpaul@localhost:7003/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
info: #为eureka提供微服务信息
  app.name: springcloud-demo
  company.name: www.yangpaul.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---

server:
  port: 8001
spring:
  profiles: beta
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yangpaul8001?useSSL=false&serverTimezone=GMT
    username: root
    password: yangpaul
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: config-dept-client
eureka:
  client:
    service-url:
      defaultZone: http://yangpaul:yangpaul@localhost:7001/eureka,http://yangpaul:yangpaul@localhost:7002/eureka,http://yangpaul:yangpaul@localhost:7003/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
info: #为eureka提供微服务信息
  app.name: springcloud-demo
  company.name: www.yangpaul.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$