spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: eureka-7001
eureka:
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理间隔时间，默认为60S
  client:
    service-url:
      defaultZone: http://yangpaul:yangpaul@localhost:7002/eureka,http://yangpaul:yangpaul@localhost:7003/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: http://localhost:7001
security:
  basic:
    enabled: true
  user:
    name: yangpaul
    password: yangpaul
---
server:
  port: 7001
spring:
  profiles: beta
  application:
    name: eureka-7001
eureka:
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理间隔时间，默认为60S
  client:
    service-url:
      defaultZone: http://yangpaul:yangpaul@localhost:7002/eureka,http://yangpaul:yangpaul@localhost:7003/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: http://localhost:7001
security:
  basic:
    enabled: true
  user:
    name: yangpaul
    password: yangpaul
